name: CI
on:
  push:
    branches: [ master ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Create a new release
        run: |
          curl \
            --silent \
            --show-error \
            --request POST \
            --user antelle:$BINTRAY_API_KEY \
            --header "Content-Type: application/json" \
            --data "{\"name\":\"$COMMIT_SHA\"}" \
            https://api.bintray.com/packages/antelle/generic/keeweb-native-modules/versions
#  build-linux:
#    runs-on: ubuntu-latest
#    needs: prepare
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: sudo apt-get install libudev-dev
#      - name: NPM install
#        run: npm i --no-fund
#      - name: Cleanup
#        run: rm -rf node_modules/usb/build/Release
#      - name: Build
#        run: npm run-script build
#      - name: Check
#        run: ls -l node_modules/usb/build/Release
#  build-darwin:
#    runs-on: macos-latest
#    needs: prepare
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: brew install libuv
#      - name: NPM install
#        run: npm i --no-fund
#      - name: Cleanup
#        run: rm -rf node_modules/usb/build/Release
#      - name: Build
#        run: npm run-script build
#      - name: Check
#        run: ls -l node_modules/usb/build/Release
#  build-windows:
#    runs-on: windows-latest
#    needs: prepare
#    steps:
#      - uses: actions/checkout@v2
#      - name: NPM install
#        run: npm i --no-fund
#      - name: Cleanup
#        run: rm -rf node_modules\usb\build\Release
#      - name: Build
#        run: npm run-script build
#      - name: Check
#        run: ls -l node_modules\usb\build\Release

