name: CI
on:
  push:
    branches: [ master ]
jobs:
#  linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: sudo apt-get install libudev-dev
#      - name: NPM install
#        run: npm i --no-fund
#      - name: Cleanup
#        run: rm -rf node_modules/usb/build/Release
#      - name: Build
#        run: npm run-script build
#      - name: Check
#        run: ls -l node_modules/usb/build/Release
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install libuv
      - name: NPM install
        run: npm i --no-fund
      - name: Cleanup
        run: rm -rf node_modules/usb/build/Release
      - name: Build
        run: npm run-script build
      - name: Check
        run: ls -l node_modules/usb/build/Release
